const fs = require('fs');

const spritesFile = './src/sprites.ts';
let content = fs.readFileSync(spritesFile, 'utf8');

// We will use regex to replace WEAPON_SPRITES and ARMOR_SPRITES objects.
// Since it's a TS file, we can just replace everything from `export const WEAPON_SPRITES` to the start of `export const ARMOR_SPRITES`
// and from `export const ARMOR_SPRITES` to `export const drawIconSprite`.

const weaponSpritesCode = `export const WEAPON_SPRITES: Record<string, string[]> = {
  'w_craft_ragnarok': [
    "       !!       ",
    "      !wm!      ",
    "      !mw!      ",
    "     !!wm!!     ",
    "     !mwwm!     ",
    "    !!wmwm!!    ",
    "    !wwmwmw!    ",
    "   !!mwmwwm!!   ",
    "   !wwmwwmww!   ",
    "  ##!mmwwmm!##  ",
    " #P##!mmmm!##P# ",
    "  #PP#!ww!#PP#  ",
    "   ###!ww!###   ",
    "      #PP#      ",
    "      #pp#      ",
    "       ##       ",
  ],
  'w_wood_sword': [
    "                ",
    "       ##       ",
    "      #YY#      ",
    "      #tt#      ",
    "      #Yt#      ",
    "      #tt#      ",
    "      #tY#      ",
    "      #tt#      ",
    "     ##tt##     ",
    "    #YTTTTY#    ",
    "     ##TT##     ",
    "      #tY#      ",
    "      #tt#      ",
    "      #TT#      ",
    "       ##       ",
    "                ",
  ],
  'w_iron_sword': [
    "       ##       ",
    "      #wg#      ",
    "      #ww#      ",
    "      #gw#      ",
    "      #wg#      ",
    "      #gw#      ",
    "      #wg#      ",
    "      #gw#      ",
    "     ##ww##     ",
    "    #GGggGG#    ",
    "     ##GG##     ",
    "      #tY#      ",
    "      #tY#      ",
    "      #YY#      ",
    "       ##       ",
    "                ",
  ],
  'w_bronze_spear': [
    "       ##       ",
    "      #yy#      ",
    "     #yyyy#     ",
    "     #yYYy#     ",
    "      #YY#      ",
    "      #tt#      ",
    "      #tY#      ",
    "      #tt#      ",
    "      #tY#      ",
    "      #tt#      ",
    "      #tY#      ",
    "      #tt#      ",
    "      #tY#      ",
    "      #tt#      ",
    "      #TT#      ",
    "       ##       ",
  ],
  'w_silver_rapier': [
    "       ##       ",
    "       #w#      ",
    "       #g#      ",
    "       #w#      ",
    "       #g#      ",
    "       #w#      ",
    "       #g#      ",
    "       #w#      ",
    "      ##w##     ",
    "     #bgwgb#    ",
    "     #BBGBB#    ",
    "       #t#      ",
    "       #Y#      ",
    "      #BBB#     ",
    "       ###      ",
    "                ",
  ],
  'w_thief_dagger': [
    "                ",
    "                ",
    "                ",
    "       ##       ",
    "      #gw#      ",
    "      #wg#      ",
    "      #gw#      ",
    "      #wg#      ",
    "     ##ww##     ",
    "    #dGGGGd#    ",
    "      #YY#      ",
    "      #tt#      ",
    "      #dd#      ",
    "       ##       ",
    "                ",
    "                ",
  ],
  'w_scholar_wand': [
    "       ##       ",
    "      #bb#      ",
    "     #bwwb#     ",
    "     #bwwb#     ",
    "      #bb#      ",
    "     ##YY##     ",
    "      #tt#      ",
    "      #Yt#      ",
    "      #tt#      ",
    "      #tY#      ",
    "      #tt#      ",
    "      #Yt#      ",
    "      #tt#      ",
    "      #YY#      ",
    "       ##       ",
    "                ",
  ],
  'w_ice_blade': [
    "       ##       ",
    "      #wb#      ",
    "      #bw#      ",
    "      #wi#      ",
    "      #bw#      ",
    "     ##wi##     ",
    "    #bwwiib#    ",
    "    #wwiiww#    ",
    "     ##ww##     ",
    "    #iBBBBi#    ",
    "    #bbBBbb#    ",
    "      #BB#      ",
    "      #BB#      ",
    "      #bb#      ",
    "       ##       ",
    "                ",
  ],
  'w_gold_sword': [
    "       ##       ",
    "      #w!#      ",
    "      #!y#      ",
    "      #yY#      ",
    "      #!y#      ",
    "      #yY#      ",
    "      #!y#      ",
    "      #yY#      ",
    "     ##!!##     ",
    "    #YyyyyY#    ",
    "    #YYyyYY#    ",
    "      #tt#      ",
    "      #tt#      ",
    "      #YY#      ",
    "       ##       ",
    "                ",
  ],
  'w_thunder_axe': [
    "     ######     ",
    "    #!!##!!#    ",
    "   #!!!!w!!!#   ",
    "   #!!yyyy!!#   ",
    "    #YyyyyY#    ",
    "     #YttY#     ",
    "      #tY#      ",
    "      #tt#      ",
    "      #tY#      ",
    "      #tt#      ",
    "      #tY#      ",
    "      #tt#      ",
    "      #YY#      ",
    "      #YY#      ",
    "       ##       ",
    "                ",
  ],
  'w_vampire_blade': [
    "       ##       ",
    "      #rR#      ",
    "      #Rr#      ",
    "      #rM#      ",
    "      #MR#      ",
    "      #rM#      ",
    "      #MR#      ",
    "      #rM#      ",
    "     ##rR##     ",
    "    #MMMmmM#    ",
    "    #RRMMRR#    ",
    "      #dD#      ",
    "      #dd#      ",
    "      #MM#      ",
    "       ##       ",
    "                ",
  ],
  'w_shadow_scythe': [
    "    #######     ",
    "   #PppppP#     ",
    "  #PpP##ppP#    ",
    "  #PP#  #Ppp#   ",
    "   ##    #Pp#   ",
    "         #dd#   ",
    "         #dd#   ",
    "         #dd#   ",
    "        ##dd##  ",
    "       #DDddDD# ",
    "         #dd#   ",
    "         #dd#   ",
    "         #dd#   ",
    "         #DD#   ",
    "          ##    ",
    "                ",
  ],
  'w_flame_sword': [
    "       ##       ",
    "      #yY#      ",
    "     #yYY#      ",
    "     #YYO#      ",
    "      #OY#      ",
    "     #YoY#      ",
    "     #YYy#      ",
    "      #Yy#      ",
    "    ###YY###    ",
    "    #OYYYOO#    ",
    "    #OOOOOO#    ",
    "      #dd#      ",
    "      #dd#      ",
    "       ##       ",
    "                ",
    "                ",
  ],
  'w_excalibur': [
    "       ##       ",
    "      #w!#      ",
    "      #!b#      ",
    "      #wb#      ",
    "      #bw#      ",
    "      #wb#      ",
    "      #bw#      ",
    "      #wb#      ",
    "    ###b!###    ",
    "   #y!!bbb!!y#  ",
    "   #yYYYYYYy#   ",
    "      #yy#      ",
    "      #yY#      ",
    "      #YY#      ",
    "       ##       ",
    "                ",
  ],
  'w_dragon_slayer': [
    "      ####      ",
    "     #wwww#     ",
    "     #wRRw#     ",
    "     #RwwR#     ",
    "     #GRRG#     ",
    "     #GRRG#     ",
    "     #GRRG#     ",
    "     #GRRG#     ",
    "    ##GRRG##    ",
    "   #YYGRRGYY#   ",
    "   #YYYYYYYY#   ",
    "      #TT#      ",
    "      #TT#      ",
    "      #YY#      ",
    "       ##       ",
    "                ",
  ],
  'w_cursed_blade': [
    "       ##       ",
    "      #P!#      ",
    "      #PP#      ",
    "      #Pd#      ",
    "      #dP#      ",
    "      #PP#      ",
    "      #Pd#      ",
    "      #dP#      ",
    "     ##PP##     ",
    "    #dPP!Pd#    ",
    "     ##dd##     ",
    "      #dP#      ",
    "      #dd#      ",
    "      #PP#      ",
    "       ##       ",
    "                ",
  ],
  'w_blood_scythe': [
    "    #######     ",
    "   #RrrrrR#     ",
    "  #RrR##rrR#    ",
    "  #RR#  #Rrr#   ",
    "   ##    #Rr#   ",
    "         #MM#   ",
    "         #MM#   ",
    "         #MM#   ",
    "        ##MM##  ",
    "       #dDMMDd# ",
    "         #MM#   ",
    "         #MM#   ",
    "         #MM#   ",
    "         #dd#   ",
    "          ##    ",
    "                ",
  ],
  'w_abyssal_blade': [
    "       ##       ",
    "      #dP#      ",
    "      #Pd#      ",
    "      #dd#      ",
    "      #PP#      ",
    "      #Pd#      ",
    "      #dP#      ",
    "      #dd#      ",
    "     ##PP##     ",
    "    #PPPPPP#    ",
    "    #ddPPdd#    ",
    "      #dD#      ",
    "      #dD#      ",
    "      #PP#      ",
    "       ##       ",
    "                ",
  ]
};

export const ARMOR_SPRITES: Record<string, string[]> = {
`;

const armorSpritesCode = `
  'a_craft_aegis': [
    "   ##########   ",
    "  #YbbbbbbbbY#  ",
    " #YbwwwwwwwwbY# ",
    " #YbwEbbbbEwbY# ",
    " #YbwbbbbbbwbY# ",
    " #bwwybbbbwyyb# ",
    " #bwyywbbwybwb# ",
    " #bwbbywwbybwb# ",
    " #bwbbbwybyywb# ",
    " #bwwybbbbwyyb# ",
    " #YbwwwwwwwwbY# ",
    "  #YbbbbbbbbY#  ",
    "  #YbbbbbbbbY#  ",
    "   #YbbbbbbY#   ",
    "    #YbbbbY#    ",
    "     #YbbY#     ",
  ],
  'a_cloth': [
    "     ######     ",
    "    #YYYYYY#    ",
    "   #YYhhhhYY#   ",
    "   #YhEhhhEY#   ",
    "   #YhehhheY#   ",
    "    #YhhhhY#    ",
    "    #cCcCcC#    ",
    "   #cCccccCc#   ",
    "   #CccCCcce#   ",
    "   #eCccCccC#   ",
    "   #eCcCCcce#   ",
    "   #CccccccC#   ",
    "   #C#    #C#   ",
    "   #C#    #C#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_leather': [
    "     ######     ",
    "    #YYYYYY#    ",
    "   #YYhhhhYY#   ",
    "   #YhEhhhEY#   ",
    "   #YhehhheY#   ",
    "    #YhhhhY#    ",
    "    #tTTtTT#    ",
    "   #tTttttTt#   ",
    "   #TttTTtte#   ",
    "   #eTttTttT#   ",
    "   #eTtTTtte#   ",
    "   #tTTTTTTt#   ",
    "   #T#    #T#   ",
    "   #T#    #T#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_chain_mail': [
    "     ######     ",
    "    #gggggg#    ",
    "   #gGhhhhGg#   ",
    "   #ghEhhhEg#   ",
    "   #ghehhheg#   ",
    "    #gGhhGg#    ",
    "    #gGgGgG#    ",
    "   #GggGGggG#   ",
    "   #ggGggGgge#  ",
    "   #eGggGGggG#  ",
    "   #egGggGgge#  ",
    "   #GggggggG#   ",
    "   #g#    #g#   ",
    "   #G#    #G#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_iron': [
    "     ######     ",
    "    #GggggG#    ",
    "   #gGhhhhGg#   ",
    "   #ghEhhhEg#   ",
    "   #ghehhheg#   ",
    "    #gGhhGg#    ",
    "    #GgGGgG#    ",
    "   #ggGwwGgg#   ",
    "   #gGGwwGGg#   ",
    "   #GggwwggG#   ",
    "   #GGggggGG#   ",
    "   #gGGGGGGg#   ",
    "   #g#    #g#   ",
    "   #G#    #G#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_silver_mail': [
    "     ######     ",
    "    #bbbbbb#    ",
    "   #bwghhgw#    ",
    "   #bwhEhhEw#   ",
    "   #bwhehhew#   ",
    "    #bwhhwb#    ",
    "    #wbbbbw#    ",
    "   #bwbwwbwb#   ",
    "   #bbwwwwbb#   ",
    "   #bbwwwwbb#   ",
    "   #bwbbbbwb#   ",
    "   #wbbbbbbw#   ",
    "   #b#    #b#   ",
    "   #b#    #b#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_blessed_robe': [
    "     ######     ",
    "    #wwwwww#    ",
    "   #wwhhhhw#    ",
    "   #whEhhhEw#   ",
    "   #whehhhew#   ",
    "    #whhhhw#    ",
    "    #wwyyww#    ",
    "   #wyywwyyw#   ",
    "   #wywwwwyw#   ",
    "   #wwywwyww#   ",
    "   #wwwyywww#   ",
    "   #wwwwwwww#   ",
    "   #w#    #w#   ",
    "   #w#    #w#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_fairy_robe': [
    "     ######     ",
    "    #pppppp#    ",
    "   #pphhhhpp#   ",
    "   #phEhhhEp#   ",
    "   #phehhhep#   ",
    "    #phhhhp#    ",
    "    #pPPPPp#    ",
    "   #PppPPppP#   ",
    "   #PpPPPPpP#   ",
    "   #PPppppPP#   ",
    "   #PppppppP#   ",
    "   #PPPPPPPP#   ",
    "   #P#    #P#   ",
    "   #p#    #p#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_gold': [
    "     ######     ",
    "    #YyyyyY#    ",
    "   #YyhhhhYy#   ",
    "   #yYhEhhEY#   ",
    "   #yYhehhheY#  ",
    "    #yYhhYy#    ",
    "    #YyYYyY#    ",
    "   #yyY!!Yyy#   ",
    "   #yYY!!YYy#   ",
    "   #Yyy!!yyY#   ",
    "   #YYyyyyYY#   ",
    "   #yYYYYYYy#   ",
    "   #y#    #y#   ",
    "   #Y#    #Y#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_dragon_scale': [
    "     #R##R#     ",
    "    #RrRRrR#    ",
    "   #RrhhhhR#    ",
    "   #RhEhhhER#   ",
    "   #RhehhheR#   ",
    "    #RhhhhR#    ",
    "    #rRrRrR#    ",
    "   #RRrRRrRR#   ",
    "   #rRrRRrRr#   ",
    "   #RRrRRrRR#   ",
    "   #rRrRRrRr#   ",
    "   #RRRRRRRR#   ",
    "   #R#    #R#   ",
    "   #r#    #r#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_hero_plate': [
    "     ######     ",
    "    #yBBBBy#    ",
    "   #bBhhhhBb#   ",
    "   #BhEhhhEB#   ",
    "   #BhehhheB#   ",
    "    #bBhhBb#    ",
    "    #bBBBBb#    ",
    "   #BbyyyybB#   ",
    "   #BbByyBbB#   ",
    "   #bBbyybBb#   ",
    "   #BBbbbbBB#   ",
    "   #bBBBBBBb#   ",
    "   #B#    #B#   ",
    "   #b#    #b#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_aegis_plate': [
    "     ######     ",
    "    #IIIIII#    ",
    "   #IihhhhIi#   ",
    "   #IhEhhhEI#   ",
    "   #IhehhheI#   ",
    "    #IihhIi#    ",
    "    #iIIIIi#    ",
    "   #IiwIIwiI#   ",
    "   #IiIwwIiI#   ",
    "   #iIiwIiwIi#  ",
    "   #IIiiiiII#   ",
    "   #iIIIIIIi#   ",
    "   #I#    #I#   ",
    "   #i#    #i#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_dark': [
    "     #P##P#     ",
    "    #PPddPP#    ",
    "   #PdhhhhPd#   ",
    "   #dhEhhhEd#   ",
    "   #dhehhhed#   ",
    "    #PdhhPd#    ",
    "    #dPddPd#    ",
    "   #PdPPPPdP#   ",
    "   #dPddddPd#   ",
    "   #PdPPPPdP#   ",
    "   #dPddddPd#   ",
    "   #ddPPPPdd#   ",
    "   #P#    #P#   ",
    "   #d#    #d#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_celestial_armor': [
    "     #!##!#     ",
    "    #w!ww!w#    ",
    "   #w!hhhh!w#   ",
    "   #!hEhhhE!#   ",
    "   #!hehhhe!#   ",
    "    #!hhhh!#    ",
    "    #wwwwww#    ",
    "   #w!wbbw!w#   ",
    "   #w!bbbb!w#   ",
    "   #w!wbbw!w#   ",
    "   #ww!ww!ww#   ",
    "   #w!wwww!w#   ",
    "   #w#    #w#   ",
    "   #!#    #!#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_cursed_mail': [
    "     ######     ",
    "    #PPPPPP#    ",
    "   #PPhhhhPP#   ",
    "   #PhEhhhEP#   ",
    "   #PhehhheP#   ",
    "    #PdhhdP#    ",
    "    #PdPPdP#    ",
    "   #PddPPddP#   ",
    "   #ddPPPPdd#   ",
    "   #PddPPddP#   ",
    "   #ddPPPPdd#   ",
    "   #PddddddP#   ",
    "   #d#    #d#   ",
    "   #P#    #P#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_abyssal_carapace': [
    "     #d##d#     ",
    "    #dPddPd#    ",
    "   #PdhhhhdP#   ",
    "   #dhEhhhEd#   ",
    "   #dhehhhed#   ",
    "    #dPhhPd#    ",
    "    #ddPPdd#    ",
    "   #dPddddPd#   ",
    "   #PdPPPPdP#   ",
    "   #dPddddPd#   ",
    "   #PdPPPPdP#   ",
    "   #ddPPPPdd#   ",
    "   #P#    #P#   ",
    "   #d#    #d#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_soul_drainer': [
    "     ######     ",
    "    #MMMMMM#    ",
    "   #MMhhhhMM#   ",
    "   #MhEhhhEM#   ",
    "   #MhehhheM#   ",
    "    #MhRRhM#    ",
    "    #MMRRMM#    ",
    "   #MmMmMMmM#   ",
    "   #mmRRRRmm#   ",
    "   #MmMmMMmM#   ",
    "   #mmRRRRmm#   ",
    "   #MmmmmmmM#   ",
    "   #m#    #m#   ",
    "   #M#    #M#   ",
    "   ###    ###   ",
    "                ",
  ]
};
`;

const weaponRegex = /export const WEAPON_SPRITES: Record<string, string\[\]> = \{[\s\S]*?export const ARMOR_SPRITES: Record<string, string\[\]> = \{/;
content = content.replace(weaponRegex, weaponSpritesCode);

const armorRegex = /export const ARMOR_SPRITES: Record<string, string\[\]> = \{[\s\S]*?\};\n\nexport const drawIconSprite/;
content = content.replace(armorRegex, armorSpritesCode + '\nexport const drawIconSprite');

fs.writeFileSync(spritesFile, content);
console.log('Successfully updated sprites.ts');
