#!/bin/bash
# Insert imports at the top
sed -i 's|import { useCloudSave } from '"'"'./useCloudSave'"'"';|import { useCloudSave } from '"'"'./useCloudSave'"'"';\nimport { db, auth } from '"'"'./firebase'"'"';\nimport { doc, getDoc, updateDoc, setDoc, increment } from '"'"'firebase/firestore'"'"';|' src/App.tsx

# Create a function to update weekly focus time
# We can inject this right before `handleTimerComplete`
sed -i '/const handleTimerComplete = () => {/i \
  const updateWeeklyFocusTime = async (minutes: number) => {\n    if (!auth.currentUser) return;\n    const currentWeekId = `2026-W${Math.floor(Date.now() / (7 * 24 * 60 * 60 * 1000))}`;\n    try {\n      const userRef = doc(db, "users", auth.currentUser.uid);\n      const userSnap = await getDoc(userRef);\n      if (userSnap.exists()) {\n        const data = userSnap.data();\n        if (data.weekId !== currentWeekId) {\n          await updateDoc(userRef, {\n            weekId: currentWeekId,\n            weeklyFocusTime: minutes,\n            totalFocusTime: increment(minutes)\n          });\n          if (data.guildId) {\n            const guildRef = doc(db, "guilds", data.guildId);\n            const guildSnap = await getDoc(guildRef);\n            if (guildSnap.exists()) {\n              if (guildSnap.data().weekId !== currentWeekId) {\n                await updateDoc(guildRef, { weekId: currentWeekId, weeklyFocusTime: minutes });\n              } else {\n                await updateDoc(guildRef, { weeklyFocusTime: increment(minutes) });\n              }\n            }\n          }\n        } else {\n          await updateDoc(userRef, { \n            weeklyFocusTime: increment(minutes),\n            totalFocusTime: increment(minutes)\n          });\n          if (data.guildId) {\n            const guildRef = doc(db, "guilds", data.guildId);\n            const guildSnap = await getDoc(guildRef);\n            if (guildSnap.exists()) {\n              if (guildSnap.data().weekId !== currentWeekId) {\n                await updateDoc(guildRef, { weekId: currentWeekId, weeklyFocusTime: minutes });\n              } else {\n                await updateDoc(guildRef, { weeklyFocusTime: increment(minutes) });\n              }\n            }\n          }\n        }\n      } else {\n        await setDoc(userRef, {\n          displayName: auth.currentUser.displayName || "名無し勇者",\n          weeklyFocusTime: minutes,\n          totalFocusTime: minutes,\n          weekId: currentWeekId,\n          guildId: ""\n        });\n      }\n    } catch (e) {\n      console.error("Failed to update weekly focus time", e);\n    }\n  };\n' src/App.tsx

# Call updateWeeklyFocusTime in handleTimerComplete
sed -i 's|setInventory(prev => \[\.\.\.prev, newChestItem\]);|setInventory(prev => [...prev, newChestItem]);\n      updateWeeklyFocusTime(focusMinutes);|' src/App.tsx
