github.com:
    users:
        1919114514yasenpai-maker:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: 1919114514yasenpai-maker
