export const ARMOR_SPRITES: Record<string, string[]> = {
  'a_deep_armor': [
    "   ##########   ",
    "  #PmmmmmmmmP#  ",
    " #PmwbbbbbbwmP# ",
    " #PmbwmmmwmbmP# ",
    " #PmbmbmbmbwmP# ",
    " #mwwmbbbbmwwm# ",
    " #mbwwmbbmwwbm# ",
    " #mbmbwwmwwmbm# ",
    " #mbmmmwmwwybm# ",
    " #mwwmbbbbmwwm# ",
    " #PmwbbbbbbwmP# ",
    "  #PmmmmmmmmP#  ",
    "  #PbbbbbbbbP#  ",
    "   #PbbbbbbP#   ",
    "    #PbbbbP#    ",
    "     #PbbP#     ",
  ],
  'a_craft_aegis': [
    "   ##########   ",
    "  #YbbbbbbbbY#  ",
    " #YbwwwwwwwwbY# ",
    " #YbwEbbbbEwbY# ",
    " #YbwbbbbbbwbY# ",
    " #bwwybbbbwyyb# ",
    " #bwyywbbwybwb# ",
    " #bwbbywwbybwb# ",
    " #bwbbbwybyywb# ",
    " #bwwybbbbwyyb# ",
    " #YbwwwwwwwwbY# ",
    "  #YbbbbbbbbY#  ",
    "  #YbbbbbbbbY#  ",
    "   #YbbbbbbY#   ",
    "    #YbbbbY#    ",
    "     #YbbY#     ",
  ],
  'a_cloth': [
    "     ######     ",
    "    #YYYYYY#    ",
    "   #YYhhhhYY#   ",
    "   #YhEhhhEY#   ",
    "   #YhehhheY#   ",
    "    #YhhhhY#    ",
    "    #cCcCcC#    ",
    "   #cCccccCc#   ",
    "   #CccCCcce#   ",
    "   #eCccCccC#   ",
    "   #eCcCCcce#   ",
    "   #CccccccC#   ",
    "   #C#    #C#   ",
    "   #C#    #C#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_leather': [
    "     ######     ",
    "    #YYYYYY#    ",
    "   #YYhhhhYY#   ",
    "   #YhEhhhEY#   ",
    "   #YhehhheY#   ",
    "    #YhhhhY#    ",
    "    #tTTtTT#    ",
    "   #tTttttTt#   ",
    "   #TttTTtte#   ",
    "   #eTttTttT#   ",
    "   #eTtTTtte#   ",
    "   #tTTTTTTt#   ",
    "   #T#    #T#   ",
    "   #T#    #T#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_chain_mail': [
    "     ######     ",
    "    #gggggg#    ",
    "   #gGhhhhGg#   ",
    "   #ghEhhhEg#   ",
    "   #ghehhheg#   ",
    "    #gGhhGg#    ",
    "    #gGgGgG#    ",
    "   #GggGGggG#   ",
    "   #ggGggGgge#  ",
    "   #eGggGGggG#  ",
    "   #egGggGgge#  ",
    "   #GggggggG#   ",
    "   #g#    #g#   ",
    "   #G#    #G#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_iron': [
    "     ######     ",
    "    #GggggG#    ",
    "   #gGhhhhGg#   ",
    "   #ghEhhhEg#   ",
    "   #ghehhheg#   ",
    "    #gGhhGg#    ",
    "    #GgGGgG#    ",
    "   #ggGwwGgg#   ",
    "   #gGGwwGGg#   ",
    "   #GggwwggG#   ",
    "   #GGggggGG#   ",
    "   #gGGGGGGg#   ",
    "   #g#    #g#   ",
    "   #G#    #G#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_silver_mail': [
    "     ######     ",
    "    #bbbbbb#    ",
    "   #bwghhgw#    ",
    "   #bwhEhhEw#   ",
    "   #bwhehhew#   ",
    "    #bwhhwb#    ",
    "    #wbbbbw#    ",
    "   #bwbwwbwb#   ",
    "   #bbwwwwbb#   ",
    "   #bbwwwwbb#   ",
    "   #bwbbbbwb#   ",
    "   #wbbbbbbw#   ",
    "   #b#    #b#   ",
    "   #b#    #b#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_blessed_robe': [
    "     ######     ",
    "    #wwwwww#    ",
    "   #wwhhhhw#    ",
    "   #whEhhhEw#   ",
    "   #whehhhew#   ",
    "    #whhhhw#    ",
    "    #wwyyww#    ",
    "   #wyywwyyw#   ",
    "   #wywwwwyw#   ",
    "   #wwywwyww#   ",
    "   #wwwyywww#   ",
    "   #wwwwwwww#   ",
    "   #w#    #w#   ",
    "   #w#    #w#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_fairy_robe': [
    "     ######     ",
    "    #pppppp#    ",
    "   #pphhhhpp#   ",
    "   #phEhhhEp#   ",
    "   #phehhhep#   ",
    "    #phhhhp#    ",
    "    #pPPPPp#    ",
    "   #PppPPppP#   ",
    "   #PpPPPPpP#   ",
    "   #PPppppPP#   ",
    "   #PppppppP#   ",
    "   #PPPPPPPP#   ",
    "   #P#    #P#   ",
    "   #p#    #p#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_gold': [
    "     ######     ",
    "    #YyyyyY#    ",
    "   #YyhhhhYy#   ",
    "   #yYhEhhEY#   ",
    "   #yYhehhheY#  ",
    "    #yYhhYy#    ",
    "    #YyYYyY#    ",
    "   #yyY!!Yyy#   ",
    "   #yYY!!YYy#   ",
    "   #Yyy!!yyY#   ",
    "   #YYyyyyYY#   ",
    "   #yYYYYYYy#   ",
    "   #y#    #y#   ",
    "   #Y#    #Y#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_dragon_scale': [
    "     #R##R#     ",
    "    #RrRRrR#    ",
    "   #RrhhhhR#    ",
    "   #RhEhhhER#   ",
    "   #RhehhheR#   ",
    "    #RhhhhR#    ",
    "    #rRrRrR#    ",
    "   #RRrRRrRR#   ",
    "   #rRrRRrRr#   ",
    "   #RRrRRrRR#   ",
    "   #rRrRRrRr#   ",
    "   #RRRRRRRR#   ",
    "   #R#    #R#   ",
    "   #r#    #r#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_hero_plate': [
    "     ######     ",
    "    #yBBBBy#    ",
    "   #bBhhhhBb#   ",
    "   #BhEhhhEB#   ",
    "   #BhehhheB#   ",
    "    #bBhhBb#    ",
    "    #bBBBBb#    ",
    "   #BbyyyybB#   ",
    "   #BbByyBbB#   ",
    "   #bBbyybBb#   ",
    "   #BBbbbbBB#   ",
    "   #bBBBBBBb#   ",
    "   #B#    #B#   ",
    "   #b#    #b#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_aegis_plate': [
    "     ######     ",
    "    #IIIIII#    ",
    "   #IihhhhIi#   ",
    "   #IhEhhhEI#   ",
    "   #IhehhheI#   ",
    "    #IihhIi#    ",
    "    #iIIIIi#    ",
    "   #IiwIIwiI#   ",
    "   #IiIwwIiI#   ",
    "   #iIiwIiwIi#  ",
    "   #IIiiiiII#   ",
    "   #iIIIIIIi#   ",
    "   #I#    #I#   ",
    "   #i#    #i#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_dark': [
    "     #P##P#     ",
    "    #PPddPP#    ",
    "   #PdhhhhPd#   ",
    "   #dhEhhhEd#   ",
    "   #dhehhhed#   ",
    "    #PdhhPd#    ",
    "    #dPddPd#    ",
    "   #PdPPPPdP#   ",
    "   #dPddddPd#   ",
    "   #PdPPPPdP#   ",
    "   #dPddddPd#   ",
    "   #ddPPPPdd#   ",
    "   #P#    #P#   ",
    "   #d#    #d#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_celestial_armor': [
    "     #!##!#     ",
    "    #w!ww!w#    ",
    "   #w!hhhh!w#   ",
    "   #!hEhhhE!#   ",
    "   #!hehhhe!#   ",
    "    #!hhhh!#    ",
    "    #wwwwww#    ",
    "   #w!wbbw!w#   ",
    "   #w!bbbb!w#   ",
    "   #w!wbbw!w#   ",
    "   #ww!ww!ww#   ",
    "   #w!wwww!w#   ",
    "   #w#    #w#   ",
    "   #!#    #!#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_cursed_mail': [
    "     ######     ",
    "    #PPPPPP#    ",
    "   #PPhhhhPP#   ",
    "   #PhEhhhEP#   ",
    "   #PhehhheP#   ",
    "    #PdhhdP#    ",
    "    #PdPPdP#    ",
    "   #PddPPddP#   ",
    "   #ddPPPPdd#   ",
    "   #PddPPddP#   ",
    "   #ddPPPPdd#   ",
    "   #PddddddP#   ",
    "   #d#    #d#   ",
    "   #P#    #P#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_abyssal_carapace': [
    "     #d##d#     ",
    "    #dPddPd#    ",
    "   #PdhhhhdP#   ",
    "   #dhEhhhEd#   ",
    "   #dhehhhed#   ",
    "    #dPhhPd#    ",
    "    #ddPPdd#    ",
    "   #dPddddPd#   ",
    "   #PdPPPPdP#   ",
    "   #dPddddPd#   ",
    "   #PdPPPPdP#   ",
    "   #ddPPPPdd#   ",
    "   #P#    #P#   ",
    "   #d#    #d#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_soul_drainer': [
    "     ######     ",
    "    #MMMMMM#    ",
    "   #MMhhhhMM#   ",
    "   #MhEhhhEM#   ",
    "   #MhehhheM#   ",
    "    #MhRRhM#    ",
    "    #MMRRMM#    ",
    "   #MmMmMMmM#   ",
    "   #mmRRRRmm#   ",
    "   #MmMmMMmM#   ",
    "   #mmRRRRmm#   ",
    "   #MmmmmmmM#   ",
    "   #m#    #m#   ",
    "   #M#    #M#   ",
    "   ###    ###   ",
    "                ",
  ]
};
