export const WEAPON_SPRITES: Record<string, string[]> = {
  'w_deep_sword': [
    "       P!       ",
    "      Pmm!      ",
    "      mwwm      ",
    "     Pwmww!     ",
    "     mwwwm!     ",
    "    Pwmwwm!     ",
    "    mwwwwm!     ",
    "   Pwmwwwm!     ",
    "   mwwwwwm!     ",
    "  ##!mwwm!##    ",
    " #D##!mm!##D#   ",
    "  #DD#!w!#DD#   ",
    "   ###!w!###    ",
    "      #w#       ",
    "      #P#       ",
    "       #        ",
  ],
  'w_craft_ragnarok': [
    "       !!       ",
    "      !wm!      ",
    "      !mw!      ",
    "     !!wm!!     ",
    "     !mwwm!     ",
    "    !!wmwm!!    ",
    "    !wwmwmw!    ",
    "   !!mwmwwm!!   ",
    "   !wwmwwmww!   ",
    "  ##!mmwwmm!##  ",
    " #P##!mmmm!##P# ",
    "  #PP#!ww!#PP#  ",
    "   ###!ww!###   ",
    "      #PP#      ",
    "      #pp#      ",
    "       ##       ",
  ],
  'w_wood_sword': [
    "                ",
    "       ##       ",
    "      #YY#      ",
    "      #tt#      ",
    "      #Yt#      ",
    "      #tt#      ",
    "      #tY#      ",
    "      #tt#      ",
    "     ##tt##     ",
    "    #YTTTTY#    ",
    "     ##TT##     ",
    "      #tY#      ",
    "      #tt#      ",
    "      #TT#      ",
    "       ##       ",
    "                ",
  ],
  'w_iron_sword': [
    "       ##       ",
    "      #wg#      ",
    "      #ww#      ",
    "      #gw#      ",
    "      #wg#      ",
    "      #gw#      ",
    "      #wg#      ",
    "      #gw#      ",
    "     ##ww##     ",
    "    #GGggGG#    ",
    "     ##GG##     ",
    "      #tY#      ",
    "      #tY#      ",
    "      #YY#      ",
    "       ##       ",
    "                ",
  ],
  'w_bronze_spear': [
    "       ##       ",
    "      #yy#      ",
    "     #yyyy#     ",
    "     #yYYy#     ",
    "      #YY#      ",
    "      #tt#      ",
    "      #tY#      ",
    "      #tt#      ",
    "      #tY#      ",
    "      #tt#      ",
    "      #tY#      ",
    "      #tt#      ",
    "      #tY#      ",
    "      #tt#      ",
    "      #TT#      ",
    "       ##       ",
  ],
  'w_silver_rapier': [
    "       ##       ",
    "       #w#      ",
    "       #g#      ",
    "       #w#      ",
    "       #g#      ",
    "       #w#      ",
    "       #g#      ",
    "       #w#      ",
    "      ##w##     ",
    "     #bgwgb#    ",
    "     #BBGBB#    ",
    "       #t#      ",
    "       #Y#      ",
    "      #BBB#     ",
    "       ###      ",
    "                ",
  ],
  'w_thief_dagger': [
    "                ",
    "                ",
    "                ",
    "       ##       ",
    "      #gw#      ",
    "      #wg#      ",
    "      #gw#      ",
    "      #wg#      ",
    "     ##ww##     ",
    "    #dGGGGd#    ",
    "      #YY#      ",
    "      #tt#      ",
    "      #dd#      ",
    "       ##       ",
    "                ",
    "                ",
  ],
  'w_scholar_wand': [
    "       ##       ",
    "      #bb#      ",
    "     #bwwb#     ",
    "     #bwwb#     ",
    "      #bb#      ",
    "     ##YY##     ",
    "      #tt#      ",
    "      #Yt#      ",
    "      #tt#      ",
    "      #tY#      ",
    "      #tt#      ",
    "      #Yt#      ",
    "      #tt#      ",
    "      #YY#      ",
    "       ##       ",
    "                ",
  ],
  'w_ice_blade': [
    "       ##       ",
    "      #wb#      ",
    "      #bw#      ",
    "      #wi#      ",
    "      #bw#      ",
    "     ##wi##     ",
    "    #bwwiib#    ",
    "    #wwiiww#    ",
    "     ##ww##     ",
    "    #iBBBBi#    ",
    "    #bbBBbb#    ",
    "      #BB#      ",
    "      #BB#      ",
    "      #bb#      ",
    "       ##       ",
    "                ",
  ],
  'w_gold_sword': [
    "       ##       ",
    "      #w!#      ",
    "      #!y#      ",
    "      #yY#      ",
    "      #!y#      ",
    "      #yY#      ",
    "      #!y#      ",
    "      #yY#      ",
    "     ##!!##     ",
    "    #YyyyyY#    ",
    "    #YYyyYY#    ",
    "      #tt#      ",
    "      #tt#      ",
    "      #YY#      ",
    "       ##       ",
    "                ",
  ],
  'w_thunder_axe': [
    "     ######     ",
    "    #!!##!!#    ",
    "   #!!!!w!!!#   ",
    "   #!!yyyy!!#   ",
    "    #YyyyyY#    ",
    "     #YttY#     ",
    "      #tY#      ",
    "      #tt#      ",
    "      #tY#      ",
    "      #tt#      ",
    "      #tY#      ",
    "      #tt#      ",
    "      #YY#      ",
    "      #YY#      ",
    "       ##       ",
    "                ",
  ],
  'w_vampire_blade': [
    "       ##       ",
    "      #rR#      ",
    "      #Rr#      ",
    "      #rM#      ",
    "      #MR#      ",
    "      #rM#      ",
    "      #MR#      ",
    "      #rM#      ",
    "     ##rR##     ",
    "    #MMMmmM#    ",
    "    #RRMMRR#    ",
    "      #dD#      ",
    "      #dd#      ",
    "      #MM#      ",
    "       ##       ",
    "                ",
  ],
  'w_shadow_scythe': [
    "    #######     ",
    "   #PppppP#     ",
    "  #PpP##ppP#    ",
    "  #PP#  #Ppp#   ",
    "   ##    #Pp#   ",
    "         #dd#   ",
    "         #dd#   ",
    "         #dd#   ",
    "        ##dd##  ",
    "       #DDddDD# ",
    "         #dd#   ",
    "         #dd#   ",
    "         #dd#   ",
    "         #DD#   ",
    "          ##    ",
    "                ",
  ],
  'w_flame_sword': [
    "       ##       ",
    "      #yY#      ",
    "     #yYY#      ",
    "     #YYO#      ",
    "      #OY#      ",
    "     #YoY#      ",
    "     #YYy#      ",
    "      #Yy#      ",
    "    ###YY###    ",
    "    #OYYYOO#    ",
    "    #OOOOOO#    ",
    "      #dd#      ",
    "      #dd#      ",
    "       ##       ",
    "                ",
    "                ",
  ],
  'w_excalibur': [
    "       ##       ",
    "      #w!#      ",
    "      #!b#      ",
    "      #wb#      ",
    "      #bw#      ",
    "      #wb#      ",
    "      #bw#      ",
    "      #wb#      ",
    "    ###b!###    ",
    "   #y!!bbb!!y#  ",
    "   #yYYYYYYy#   ",
    "      #yy#      ",
    "      #yY#      ",
    "      #YY#      ",
    "       ##       ",
    "                ",
  ],
  'w_dragon_slayer': [
    "      ####      ",
    "     #wwww#     ",
    "     #wRRw#     ",
    "     #RwwR#     ",
    "     #GRRG#     ",
    "     #GRRG#     ",
    "     #GRRG#     ",
    "     #GRRG#     ",
    "    ##GRRG##    ",
    "   #YYGRRGYY#   ",
    "   #YYYYYYYY#   ",
    "      #TT#      ",
    "      #TT#      ",
    "      #YY#      ",
    "       ##       ",
    "                ",
  ],
  'w_cursed_blade': [
    "       ##       ",
    "      #P!#      ",
    "      #PP#      ",
    "      #Pd#      ",
    "      #dP#      ",
    "      #PP#      ",
    "      #Pd#      ",
    "      #dP#      ",
    "     ##PP##     ",
    "    #dPP!Pd#    ",
    "     ##dd##     ",
    "      #dP#      ",
    "      #dd#      ",
    "      #PP#      ",
    "       ##       ",
    "                ",
  ],
  'w_blood_scythe': [
    "    #######     ",
    "   #RrrrrR#     ",
    "  #RrR##rrR#    ",
    "  #RR#  #Rrr#   ",
    "   ##    #Rr#   ",
    "         #MM#   ",
    "         #MM#   ",
    "         #MM#   ",
    "        ##MM##  ",
    "       #dDMMDd# ",
    "         #MM#   ",
    "         #MM#   ",
    "         #MM#   ",
    "         #dd#   ",
    "          ##    ",
    "                ",
  ],
  'w_abyssal_blade': [
    "       ##       ",
    "      #dP#      ",
    "      #Pd#      ",
    "      #dd#      ",
    "      #PP#      ",
    "      #Pd#      ",
    "      #dP#      ",
    "      #dd#      ",
    "     ##PP##     ",
    "    #PPPPPP#    ",
    "    #ddPPdd#    ",
    "      #dD#      ",
    "      #dD#      ",
    "      #PP#      ",
    "       ##       ",
    "                ",
  ]
};
