export const PALETTE: Record<string, string> = {
  ' ': 'transparent',
  '#': '#0f172a',
  'w': '#ffffff',
  'g': '#94a3b8',
  'G': '#475569',
  'y': '#fcd34d',
  'Y': '#b45309',
  'r': '#fca5a5',
  'R': '#b91c1c',
  'b': '#7dd3fc',
  'B': '#0369a1',
  'p': '#d8b4fe',
  'P': '#7e22ce',
  't': '#8B4513',
  'T': '#5c2e0e',
  'd': '#1e293b',
  'h': '#ffedd5',
  'H': '#fdba74',
  'c': '#86efac',
  'C': '#15803d',
  'i': '#38bdf8',
  'I': '#0284c7',
  'm': '#f472b6',
  'M': '#be185d',
  'e': '#000000',
  'E': '#000000',
  'o': '#ea580c',
  'O': '#9a3412',
  '!': '#fef08a',
  '*': '#cffafe',
};

export const WEAPON_SPRITES: Record<string, string[]> = {
  'w_wood_sword': [
    "                ",
    "       ##       ",
    "      #tt#      ",
    "      #tt#      ",
    "      #tt#      ",
    "      #tt#      ",
    "      #tt#      ",
    "      #tt#      ",
    "      #tt#      ",
    "     ##tt##     ",
    "    #TTTTTT#    ",
    "    #TTTTTT#    ",
    "      #TT#      ",
    "      #TT#      ",
    "       ##       ",
    "                ",
  ],
  'w_iron_sword': [
    "                ",
    "       ##       ",
    "      #ww#      ",
    "      #gg#      ",
    "      #gg#      ",
    "      #gg#      ",
    "      #gg#      ",
    "      #gg#      ",
    "      #gg#      ",
    "     ##gg##     ",
    "    #GGGGGG#    ",
    "    #GGGGGG#    ",
    "      #TT#      ",
    "      #TT#      ",
    "       ##       ",
    "                ",
  ],
  'w_bronze_spear': [
    "       ##       ",
    "      #ww#      ",
    "      #yy#      ",
    "     ##yy##     ",
    "     #YyyY#     ",
    "      #YY#      ",
    "      #TT#      ",
    "      #TT#      ",
    "      #TT#      ",
    "      #TT#      ",
    "      #TT#      ",
    "      #TT#      ",
    "      #TT#      ",
    "      #TT#      ",
    "       ##       ",
    "                ",
  ],
  'w_silver_rapier': [
    "                ",
    "       ##       ",
    "      #ww#      ",
    "      #ww#      ",
    "      #ww#      ",
    "      #ww#      ",
    "      #ww#      ",
    "      #ww#      ",
    "      #ww#      ",
    "    ###ww###    ",
    "    #g#gg#g#    ",
    "    #gggggg#    ",
    "      #TT#      ",
    "      #TT#      ",
    "       ##       ",
    "                ",
  ],
  'w_thief_dagger': [
    "                ",
    "                ",
    "                ",
    "       ##       ",
    "      #ww#      ",
    "      #cc#      ",
    "      #cc##     ",
    "      #ccC#     ",
    "     ##cC#      ",
    "    #GCGG#      ",
    "     GGGG#      ",
    "      #TT#      ",
    "       ##       ",
    "                ",
    "                ",
    "                ",
  ],
  'w_scholar_wand': [
    "       ##       ",
    "      #bb#      ",
    "     #bwwb#     ",
    "      #bb#      ",
    "      #tt#      ",
    "      #tt#      ",
    "     ##tt##     ",
    "     #TttT#     ",
    "      #tt#      ",
    "      #tt#      ",
    "      #tt#      ",
    "      #tt#      ",
    "      #tt#      ",
    "      #tt#      ",
    "       ##       ",
    "                ",
  ],
  'w_ice_blade': [
    "       ##       ",
    "      #ww#      ",
    "      #bb#      ",
    "     #wbbw#     ",
    "     #wbbw#     ",
    "     #bbbb#     ",
    "     #wbbw#     ",
    "     #bbbb#     ",
    "    ##wbbw##    ",
    "    #iBiiBi#    ",
    "    #BBBBBB#    ",
    "      #TT#      ",
    "      #TT#      ",
    "       ##       ",
    "                ",
    "                ",
  ],
  'w_gold_sword': [
    "       ##       ",
    "      #ww#      ",
    "      #yy#      ",
    "      #yy#      ",
    "      #yy#      ",
    "     ##yy##     ",
    "     #yyyy#     ",
    "     #yyyy#     ",
    "    ##yyyy##    ",
    "   #YYyyyyYY#   ",
    "   #YYYYYYYY#   ",
    "      #TT#      ",
    "      #TT#      ",
    "       ##       ",
    "                ",
    "                ",
  ],
  'w_thunder_axe': [
    "                ",
    "     ####       ",
    "    #ywwy##     ",
    "   #ywwwwyy#    ",
    "   #ywwwwyy#    ",
    "   #ywwwwyy#    ",
    "    #yyyyy##    ",
    "     #TTTTT#    ",
    "        #TT#    ",
    "        #TT#    ",
    "        #TT#    ",
    "        #TT#    ",
    "        #TT#    ",
    "         ##     ",
    "                ",
    "                ",
  ],
  'w_vampire_blade': [
    "       ##       ",
    "      #ww#      ",
    "      #RR#      ",
    "      #RR##     ",
    "      #RRR#     ",
    "      #RR#      ",
    "      #RR##     ",
    "      #RRR#     ",
    "     ##RR##     ",
    "    #MMRRMM#    ",
    "    #MMMMMM#    ",
    "      #TT#      ",
    "      #TT#      ",
    "       ##       ",
    "                ",
    "                ",
  ],
  'w_shadow_scythe': [
    "     ######     ",
    "    #PPPPPP#    ",
    "   #PPppppPP#   ",
    "  #PPpp##P##    ",
    "  #Pp#    #TT#  ",
    "   ##     #TT#  ",
    "          #TT#  ",
    "          #TT#  ",
    "          #TT#  ",
    "          #TT#  ",
    "          #TT#  ",
    "          #TT#  ",
    "          #TT#  ",
    "          #TT#  ",
    "           ##   ",
    "                ",
  ],
  'w_flame_sword': [
    "       ##       ",
    "      #yR#      ",
    "     #yRR#      ",
    "     #RRo#      ",
    "      #oR#      ",
    "     #RoR#      ",
    "     #RRy#      ",
    "      #Ry#      ",
    "    ###RR###    ",
    "    #ORRROO#    ",
    "    #OOOOOO#    ",
    "      #TT#      ",
    "      #TT#      ",
    "       ##       ",
    "                ",
    "                ",
  ],
  'w_excalibur': [
    "       ##       ",
    "      #ww#      ",
    "      #bb#      ",
    "      #wb#      ",
    "      #bw#      ",
    "      #wb#      ",
    "      #bw#      ",
    "      #wb#      ",
    "    ###bw###    ",
    "   #yyybbbyy#   ",
    "   #yYYYYYYy#   ",
    "      #yy#      ",
    "      #yY#      ",
    "       ##       ",
    "                ",
    "                ",
  ],
  'w_dragon_slayer': [
    "      ####      ",
    "     #wwww#     ",
    "     #RRRR#     ",
    "     #RRRR#     ",
    "     #GGRR#     ",
    "     #GGRR#     ",
    "     #GGRR#     ",
    "     #GGRR#     ",
    "    ##GGRR##    ",
    "   #YYGGRRYY#   ",
    "   #YYYYYYYY#   ",
    "      #TT#      ",
    "      #TT#      ",
    "       ##       ",
    "                ",
    "                ",
  ],
};

export const ARMOR_SPRITES: Record<string, string[]> = {
  'a_cloth': [
    "     ######     ",
    "    #YYYYYY#    ",
    "   #YYhhhhYY#   ",
    "   #YhEhhhEY#   ",
    "   #YhehhheY#   ",
    "    #YhhhhY#    ",
    "    #CCCCCC#    ",
    "   #cCccccCc#   ",
    "   #cCccccCc#   ",
    "   #cCccccCc#   ",
    "   #cCccccCc#   ",
    "   #cCccccCc#   ",
    "   #C#    #C#   ",
    "   #C#    #C#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_leather': [
    "     ######     ",
    "    #YYYYYY#    ",
    "   #YYhhhhYY#   ",
    "   #YhEhhhEY#   ",
    "   #YhehhheY#   ",
    "    #YhhhhY#    ",
    "    #TTTTTT#    ",
    "   #TtTTTTtT#   ",
    "   #TttttttT#   ",
    "   #TttttttT#   ",
    "   #TttttttT#   ",
    "   #tTTTTTTt#   ",
    "   #T#    #T#   ",
    "   #T#    #T#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_chain_mail': [
    "     ######     ",
    "    #GGGGGG#    ",
    "   #GGhhhhGG#   ",
    "   #GhEhhhEG#   ",
    "   #GhehhheG#   ",
    "    #GhhhhG#    ",
    "    #gggggg#    ",
    "   #gGggggGg#   ",
    "   #gGggggGg#   ",
    "   #gGggggGg#   ",
    "   #gGggggGg#   ",
    "   #gGGGGGGg#   ",
    "   #G#    #G#   ",
    "   #G#    #G#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_iron': [
    "     ######     ",
    "    #gggggg#    ",
    "   #gGhhhhGg#   ",
    "   #GhEhhhEG#   ",
    "   #GhehhheG#   ",
    "    #GhhhhG#    ",
    "    #GGGGGG#    ",
    "   #GggggggG#   ",
    "   #GggGGggG#   ",
    "   #GggggggG#   ",
    "   #GGGGGGGG#   ",
    "   #GGGGGGGG#   ",
    "   #G#    #G#   ",
    "   #G#    #G#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_silver_mail': [
    "     ######     ",
    "    #wwwwww#    ",
    "   #wghhhhgw#   ",
    "   #whEhhhEw#   ",
    "   #whehhhew#   ",
    "    #whhhhw#    ",
    "    #bbbbbb#    ",
    "   #bwbbbbwb#   ",
    "   #bbbbbbbb#   ",
    "   #bwwwwwwb#   ",
    "   #bbbbbbbb#   ",
    "   #b#bbbb#b#   ",
    "   #b#    #b#   ",
    "   #b#    #b#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_blessed_robe': [
    "     ######     ",
    "    #wwwwww#    ",
    "   #wwhhhhw#    ",
    "   #whEhhhEw#   ",
    "   #whehhhew#   ",
    "    #whhhhw#    ",
    "    #wwwwww#    ",
    "   #wwyyyyww#   ",
    "   #wwyyyyww#   ",
    "   #wwwwwwww#   ",
    "   #wwwwwwww#   ",
    "   #w#wwww#w#   ",
    "   #w#    #w#   ",
    "   #w#    #w#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_fairy_robe': [
    "     ######     ",
    "    #pppppp#    ",
    "   #pphhhhpp#   ",
    "   #phEhhhEp#   ",
    "   #phehhhep#   ",
    "    #phhhhp#    ",
    "    #PPPPPP#    ",
    "   #PppppppP#   ",
    "   #PpPPPPpP#   ",
    "   #PppppppP#   ",
    "   #PPPPPPPP#   ",
    "   #P#PPPP#P#   ",
    "   #P#    #P#   ",
    "   #P#    #P#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_gold': [
    "     ######     ",
    "    #yyyyyy#    ",
    "   #yYhhhhYy#   ",
    "   #YhEhhhEY#   ",
    "   #YhehhheY#   ",
    "    #YhhhhY#    ",
    "    #YYYYYY#    ",
    "   #YyyyyyyY#   ",
    "   #YyyyyyyY#   ",
    "   #YyyyyyyY#   ",
    "   #YYYYYYYY#   ",
    "   #Y#YYYY#Y#   ",
    "   #Y#    #Y#   ",
    "   #Y#    #Y#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_dragon_scale': [
    "     #R##R#     ",
    "    #RRRRRR#    ",
    "   #RrhhhhR#    ",
    "   #RhEhhhER#   ",
    "   #RhehhheR#   ",
    "    #RhhhhR#    ",
    "    #RRRRRR#    ",
    "   #RrRRRRrR#   ",
    "   #RrRRRRrR#   ",
    "   #RrRRRRrR#   ",
    "   #RRRRRRRR#   ",
    "   #r#RRRR#r#   ",
    "   #r#    #r#   ",
    "   #r#    #r#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_hero_plate': [
    "     ######     ",
    "    #bbbbbb#    ",
    "   #yBhhhhBy#   ",
    "   #BhEhhhEB#   ",
    "   #BhehhheB#   ",
    "    #BhhhhB#    ",
    "    #BBBBBB#    ",
    "   #ByBBBByB#   ",
    "   #ByBBBByB#   ",
    "   #ByBBBByB#   ",
    "   #BBBBBBBB#   ",
    "   #B#BBBB#B#   ",
    "   #B#    #B#   ",
    "   #B#    #B#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_aegis_plate': [
    "     ######     ",
    "    #IIIIII#    ",
    "   #iIhhhhIi#   ",
    "   #IhEhhhEI#   ",
    "   #IhehhheI#   ",
    "    #IhhhhI#    ",
    "    #IIIIII#    ",
    "   #IiIIIIiI#   ",
    "   #IiIIIIiI#   ",
    "   #IiIIIIiI#   ",
    "   #IIIIIIII#   ",
    "   #I#IIII#I#   ",
    "   #I#    #I#   ",
    "   #I#    #I#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_dark': [
    "     #P##P#     ",
    "    #PPPPPP#    ",
    "   #PPhhhhPP#   ",
    "   #PhEhhhEP#   ",
    "   #PhehhheP#   ",
    "    #PhhhhP#    ",
    "    #dddddd#    ",
    "   #dPPPPPPd#   ",
    "   #dPPPPPPd#   ",
    "   #dPPPPPPd#   ",
    "   #dddddddd#   ",
    "   #d#dddd#d#   ",
    "   #d#    #d#   ",
    "   #d#    #d#   ",
    "   ###    ###   ",
    "                ",
  ],
  'a_celestial_armor': [
    "     #!##!#     ",
    "    #wwwwww#    ",
    "   #w!hhhh!w#   ",
    "   #!hEhhhE!#   ",
    "   #!hehhhe!#   ",
    "    #!hhhh!#    ",
    "    #wwwwww#    ",
    "   #w!wwww!w#   ",
    "   #w!wwww!w#   ",
    "   #w!wwww!w#   ",
    "   #wwwwwwww#   ",
    "   #w#wwww#w#   ",
    "   #w#    #w#   ",
    "   #w#    #w#   ",
    "   ###    ###   ",
    "                ",
  ],
};

export const drawIconSprite = (
  ctx: CanvasRenderingContext2D,
  sprite: string[],
  x: number,
  y: number,
  scale: number,
  isAsleep: boolean = false,
  isHit: boolean = false
) => {
  const startX = Math.floor(x);
  const startY = Math.floor(y);
  for (let r = 0; r < 16; r++) {
    for (let c = 0; c < 16; c++) {
      let char = sprite[r]?.[c] || ' ';
      if (char === ' ') continue;

      let color = PALETTE[char];
      if (isAsleep) {
        if (char === 'E') color = PALETTE['h'];
        if (char === 'e') color = PALETTE['d'];
      } else {
        if (char === 'E' || char === 'e') color = PALETTE['e'];
      }

      if (color) {
        ctx.fillStyle = isHit ? '#ef4444' : color;
        ctx.fillRect(Math.floor(startX + c * scale), Math.floor(startY + r * scale), Math.ceil(scale), Math.ceil(scale));
      }
    }
  }
};
